openapi: 3.0.0
info:
  title: PlayPower Backend Docs
  description: Documentation for API endpoints
  version: 1.0.0
servers:
  - url: http://localhost:3005/
paths:
  /auth/register:
    post:
      summary: User Registration Endpoint
      description: Endpoint for user registration.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  default: 'siva'
                email:
                  type: string
                  default: 'siva@gmail.com'
                password:
                  type: string
                  default: 'siva'
                
      responses:
        '200':
          description: User registered successfully
        '400':
          description: Error message if registration fails
  /auth/login:
    post:
      summary: User Login Endpoint
      description: Endpoint for user login.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  default: 'sivashankar'
                password:
                  type: string
                  default: 'siva'

      responses:
        '200':
          description: User logged in successfully
        '400':
          description: Error message if login fails

  /assignments/:
    post:
      summary: Add Assignment Entry
      description: Endpoint for Entry.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  default: Ass1
                description:
                  type: string
                  default: 'Maths'
                dueDate:
                  type: date
                  default: '16/08/2024'
                createdBy:
                  type: string
                  default: 'Dr. Siva'
                      
      responses:
        '200':
          description: User registered successfully
        '400':
          description: Error message if registration fails
      security:
        - bearerAuth: []   # This specifies that JWT token is required for this endpoint
    
  /assignments/get:
    get:
      summary: Assignments Data Fetching Endpoint
      description: Endpoint to fetch data.
      responses:
        '200':
          description: Successful response
        '500':
          description: Internal server error
      security:
        - bearerAuth: []   # This specifies that JWT token is required for this endpoint
  
  /assignments/upd:
    put:
      summary: Update Assignment Entry
      description: Endpoint for updating Entry.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: number
                  default: 1
                title:
                  type: string
                  default: 'Ass2'
                description:
                  type: string
                  default: 'Science Spot'
                dueDate:
                  type: date
                  default: '14/04/2024' 
                createdBy:
                  type: string
                  default: 'Mr.Siva'        
      responses:
        '200':
          description: Entry updated successfully
        '400':
          description: Error message if updation fails
      security:
        - bearerAuth: []   # This specifies that JWT token is required for this endpoint

  /assignments/delete:
    delete:
      summary: Delete Assignment Entry
      description: Endpoint for deleting Entry.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: number
                  default: 0
                         
      responses:
        '200':
          description: Entry deleted successfully
        '400':
          description: Error message if deletion fails
      security:
        - bearerAuth: []   # This specifies that JWT token is required for this endpoint
          
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT  # Optional, for documentation clarity
